build:
    image: registry.vokal.io/go1.5
    environment:
        - ENVIRONMENT=drone
        - REPO_OWNER=vokal
        - REPO_NAME=vip
    commands:
        - export GITHASH=$(git rev-parse HEAD)
        - apt-get update -qq
        - apt-get -y install bzr mercurial python-pip
        - apt-get -y install automake build-essential git gobject-introspection libglib2.0-dev libjpeg-turbo8-dev libpng12-dev gtk-doc-tools
        - git clone  --depth=50 --recursive git@github.com:vokal/q.git $GOPATH/src/github.com/vokal/q
        - git clone https://github.com/jcupitt/libvips.git
        - cd libvips
        - ./bootstrap.sh
        - ./configure --enable-debug=no --without-python --without-fftw --without-libexif --without-libgf --without-little-cms --without-orc --without-pango --prefix=/usr
        - make
        - make install
        - ldconfig
        - cd ..
        - go get
        - go get -t
        - go build
        - go test -gocheck.v -coverprofile=coverage.txt -covermode=count
        - cd fetch && go test -v -coverprofile=coverage.txt -covermode=count
        - cd ..
        - cat fetch/coverage.txt >> coverage.txt && rm fetch/coverage.txt
        - cat coverage.txt
        - export GIT_HASH=$(git rev-parse HEAD)
        - export CVR_URL="https://cvr.vokal.io/coverage?commit=$GIT_HASH&owner=$REPO_OWNER&repo=$REPO_NAME&coveragetype=cobertura"
        - curl -F coverage=@coverage.xml $CVR_URL
